### ISSUE TITLE
Set up branch autodeletion

### ISSUE THREAD

**Issue by rusheb** [mivanit/tabGPT#7]
I noticed my branches weren't deleted after merging. 

I think it would make sense to set up [automatic deletion](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches). 

@mivanit I think only you can do it due to permissions.

**Comment by mivanit** [comment]
Done! Thanks for the suggestion.
